### PR TITLE
Add new sample viewer

### PR DESCRIPTION
**Pull request by yonabystedt**
- upgraded yarn and other packages as needed to keep pace with the Web ecosystem.
- removed existing sample viewer and added a new one that uses the same code from `@vertigis/web-sdk` to build and run as the samples themselves
- linted
- added simple tests for the sample viewer

There's an issue still present with `cypress` that needs to be addressed. It can kind of be worked around here but right now it prevents loading samples other than the default, and interacting directly with the 'map' object. 

Both of these require access to the parent window of the iframe, and this isn't resolving correctly within the cypress environment. This will be a much bigger problem in the `vertigis-web-samples` repo than here.

### CODE REVIEW

**Comment by yonabystedt** [comment]
The issues with the cypress environment have been addressed. Apparently the `modifyObstructiveCode` flag (turned on by default) actually rewrites your code on the fly to break any references to the parent window.

Currently blocked because the deployment directory of the sample viewer build has changed to `/libraries/sample-viewer/build` and this needs to be reflected in the netlify configuration.

**Comment by rcooney** [comment]
Do we know what is causing the double load?

**Comment by yonabystedt** [comment]
> Do we know what is causing the double load?

Yes, it loads the first time as an empty shell before it figures out what library should be active, adjusts the configuration and reloads. Maybe it would be possible to make this seem less glitchy by suppressing the visibility of everything until it's actually ready...

**Comment by yonabystedt** [comment]
Added a loading spinner to make the initial load seem snappier and less glitchy. It only shows up on netlify or if you run `yarn serve-library-viewer` after building.

**Review by rcooney — APPROVED** [review]

**Review by rcooney — APPROVED** [review]

**Pull request merged**
